### ISSUE TITLE
6U space centered or offset switch?

### ISSUE THREAD

**Issue by o0-o** [ebastler/E80-1800#3]
My G80-1800 has an offset 6U spacebar which is very uncommon in keysets that are produced today. Will this board accommodate the much more common centered 6U?

**Comment by ebastler** [comment]
Hi, it accepts only 6u offcenter and 7u. The PCB was designed around OG cherry sets, and I had to keep compatibility to a minimum so that I do not have overlapping switches, which increase switch wobble/risk of soldering them crookedly by a lot on a plateless design.

I can see if I get the centered switch squeezed in, but not sure if that'l work out. I thought that 6u offcenter was the more common one to be honest.

**Comment by o0-o** [comment]
Yeah now that I'm looking back through key sets, I'm seeing mostly sets that have both 6U options (when they have any at all), some have a single option that isn't labelled and of course the one that I have ([BIIP](https://drop.com/buy/drop-biip-mt3-extended-custom-keycap-set)) only has a centered one. So if centered 6u is more common, it is only slightly so.

I have a 7U space and can live with that. I see your point about the stability of the pcb-mounted switches. I haven't worked on a pcb-mount board in years so I forgot about the caveats.
