### ISSUE TITLE
QMK Firmware

### ISSUE THREAD

**Issue by spooknik** [ebastler/E80-1800#4]
Hello! I noticed the [link ](https://github.com/ebastler/qmk_firmware/tree/E80_1800/keyboards/ebastler/E80_1800)in the readme for the QMK firmware links to a missing repo. I also couldn't find the firmware in the official QMK repo. 

Do you have happen to still have the firmware? 

Thanks & have a nice weekend 👍 

P.s. I forked the PCB and modified it to accept a [64X128 OLED](https://www.aliexpress.com/item/4001028369082.html?spm=a2g0o.9042311.0.0.5a554c4d7qBFis). I think it will just fit where status LEDs are on a stock 1800 case. Requires that part of the case to be removed of course.

**Comment by ebastler** [comment]
Hi! Here you go:
https://github.com/ebastler/qmk_firmware/tree/E80_1800/keyboards/ebastler/e80_1800

I think I changed the folder name from E80 to e80, to comply with QMK guidelines. Forgot to update the repo over here accordingly.

the VIA keymap compiles and works fine, the bongocat keymap is broken and I didn't find the time to get the animation running. But you'll make your own animation stuff anyway since you're using a 64x128px screen, I guess. Very curious how it will look with a screen instead of the indicators!
